id: D7AA8623C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T07:04:46+00:00'
last_modified: '2022-05-26T08:12:18.289079+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    dad4:
      image_group_id: I1PD95859
      title: བྱང་ཆུབ་ཀྱི་སེམས་བདེ་བའི་མན་ངག།
      total_pages: 1856
      order: 14
      base_file: dad4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
