id: PAAE24063
initial_creation_type: ocr
source_metadata:
  volumes:
    373ae392b2dc4ff29ca2e1fdaa427cf4:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: བྱང་ཆུབ་ཀྱི་སེམས་བདེ་བའི་མན་ངག།
      total_pages: 1856
      volume_number: 14
